import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import StoreProvider from "./store/storeProvider";
import Logout from "./components/Logout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log("insdie layout",children)
  return (
    <html lang="en">
    
      <body
        className= "flex"
      >
      <StoreProvider>
        <Sidebar/>
        <div className="flex flex-col  relative w-full h-full ">
           <div className="absolute right-10 top-4 ">
            <Logout/>
           </div>
            
        {children}
        </div>
      
        </StoreProvider>
      </body>
    </html>
  );
}
